### ISSUE TITLE
Intrinsic Calibration

### ISSUE THREAD

**Issue by muella91** [OpenPTrack/open_ptrack_v2#100]
Hello,

I got some questions/annotation to the intrinsic calibration on Kinect2

1. If I try **intrinsic calibration** for **Kinect2** **Method 1** I get the error (as mentioned in issue https://github.com/OpenPTrack/open_ptrack_v2/issues/62):
```
[FATAL] ROS_MASTER_URI is not defined in the environment. Either type the following or (preferrably) add this to your ~/.bashrc file in order set up your local machine as a ROS master:

export ROS_MASTER_URI=http://localhost:11311
```
So I used Method 2. Is method 2 as accurate as method 1?

2. The path `workspace/ros/catkin/devel/lib/kinect2_bridge` for intrinsic calibration, as mentioned here (https://github.com/OpenPTrack/open_ptrack/wiki/Intrinsic-Calibration), is actually just `workspace/ros/devel/lib/kinect2_bridge`.

3. Intrinsic calibration only needs to be done once per camera, right? Even if I change the camera positions.

4. How do I know when I took enough pictures of the checkerboard for intrinsic calibration? The guide only says keep capturing with the space bar, but not how many pictures or how many positions of the checkerboard I should take.

> Hit the space bar to capture a frame. Move the checkerboard to different positions, angles, and distances from the sensor, ensuring that the checkerboard is correctly detected. The checkerboard is being detected correctly when different colored lines overlay the checkerboard's image. Keep capturing new frames/angles with space bar.

**Comment by bsubbaraman** [comment]
Hi @muella91,

1. The two are methods equally accurate - I think that our method 1 is outdated, we have kept it for now just for completeness.
2. Thanks!
3. Yes, just once per camera for intrinsic calibration. The only time you would need to repeat intrinsic calibration is if the Kinect were dropped/hit and you notice tracking to be innacurate.
4. In the past, I have tried to capture a few dozen frames. In fact, it should be possible to capture video at a low frame rate rather than manually capture frames, which would make this process quicker - I'll look into this in the future.
