### ISSUE TITLE
Single camera Tracking not working with Kinect v1

### ISSUE THREAD

**Issue by vinay0410** [OpenPTrack/open_ptrack_v2#11]
Operating system: Ubuntu 16.04 LTS
Depth Sensor: Microsoft Kinect v1
Installed using the Doc mentioned in Readme file.

Command run: ```roslaunch tracking single_camera_tracking_node.launch```
I am not getting any camera view as attached below.
It seems as if my Kinect v1 isn't detected, but libfreenect works fine.
![screenshot from 2018-01-16 21-22-24](https://user-images.githubusercontent.com/18044818/34997772-522bdace-fb03-11e7-90f3-e52a42be162f.png)

**Comment by marketto89** [comment]
@vinay0410 thanks for your interest in OpenPTrack!

Actually, the Kinect v1 is not yet supported by the new modules we developed (object tracking, multi-person pose estimation, YOLO-based people detection). 

While its integration is not scheduled, with a basic ROS understanding, it should be possible to adapt the current launchers to work with it (in particular, the different launchers should reflect the Kinect v1 ROS topics instead of the ones for Kinect v2).

Kinect v1 should still work out-of-the-box for performing people detection with [OpenPTrack v1.0](https://github.com/openptrack/open_ptrack)

**Comment by vinay0410** [comment]
Thanks, for the reply. Actually I was using Kinect v1 and Ubuntu 16.04 LTS, so is there a successful way to run OpenPTrack on the above platforms. I thought Kinect v1 would work, because it was listed in supported hardware.

**Comment by marketto89** [comment]
We apologize, unfortunately the [new wiki](https://github.com/OpenPTrack/open_ptrack_v2/wiki) is under construction and many links point to the old [OpenPTrack v1.0 wiki](https://github.com/OpenPtrack/open_ptrack/wiki). This is why you saw that the Kinect v1 was supported.

We are planning to improve it to reflect the new supported sensors (basically Kinect v2 and ZED camera for some modules) together with the new documentation in the next weeks.

**Comment by jburkeucla** [comment]
Kinect1 support deprecated.
