### ISSUE TITLE
Getting the orientation of the skeleton joints

### ISSUE THREAD

**Issue by muella91** [OpenPTrack/open_ptrack_v2#115]
Hello,

Is it possible to get the orientation of each skeletal joint? Like in the [Kinect v2 skeleton model](https://social.msdn.microsoft.com/Forums/getfile/502013)

Since I need the other skeleton joints, I have to transfer the OPT joints into my skeleton model.  So I have to know the orientation of the skeleton joints to add an offset.

Thanks!

**Comment by muella91** [comment]
Hey, 

I am still struggling with my problem. Is it  somehow possible to  get the 6D (position+orientation) pose of each joint?
It is necessary for me to calculate further points on the body.

Edit:

```
 "persons":
   [
      {
         "id": 3,
         "height":1.50029,
         "orientation":2.4570,
         "age":29.471,
```

_Orientation is an estimation of where the person being tracked is facing in relation to OpenPTrack's 0,0 coordinate._

Does the value of "orientation" represent the angle in degree around the Z-axis of the OpenPTrack world coordinate system?

**Comment by bsubbaraman** [comment]
Hi @muella91,
For the joints, I don't believe we have any orientation information: rt_pose, which we are using for skeletons, [outputs joint positions and confidences](https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose#output-format). In the past when I have tried to (for example) animate a humanoid character using OpenPTrack, I have computed the vector between the each joint to orient my model. I found this [thread](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/228) from the openpose repo which may also be of use to you.
Please let me know if I can provide any more information or if I've misunderstood your question!

**Comment by muella91** [comment]
Thank you for your answer. I already guessed so.  I still have some small questions.
1. What does the orientation attribute of the pose estimation JSON tells me? I don't undestand the explanation. (see my post above)
2. You mentioned in https://github.com/OpenPTrack/open_ptrack_v2/issues/113 that the HEAD joint is located in the center of the head. Is the NECK joint inside the neck or is it located mid back/front in the neck? How about the CHEST joint?

I would post my solution here when I solved my problem. So you can leave the problem open if you want.

**Comment by bsubbaraman** [comment]
1. The orientation computation happens [here](https://github.com/OpenPTrack/open_ptrack_v2/blob/2fb9522510dcbe1b9101644b375c6a05fbee99b4/body_pose_recognition/standard_pose/src/standardpose.cpp#L69) in `standardpose.cpp`.  It returns the rotation around z axis of the OPT reference frame based on the joint data.

2. In the MPI model (which is what I use), there is no neck joint. I think the best way for you to find the placement is to enable the SimpleImage topic in the left hand RViz sidebar and select the` /<sensor_name>/skeleton_image ` topic, which will overlay the joints on the rgb image. That way you can empirically see where each joint is placed.

I'll keep this thread open for you to post your solution!

**Comment by mnemllr** [comment]
Okay, here's my solution to my problem. Maybe it will help others with similar problems.

- Problem: For a other joint-model I need four points on the hip bone, called left/right ASIS and PSIS. I have to calculate them from the available hip points leftHip/rightHip of the OPT rt_pose model.  For this I need not only the respective offsets but also the orientation of the hip. However, since I only have position data (x,y,z) of the joints available, I have to calculate the orientation myself.

- Solution: 
1.  From the left and right hip joint I calculate the point between the two (called spine base). 
2.  I calculate the vector from the spine base to the right hip joint point. This represents my x-axis.
3.  I calculate the plane that is spanned by the spine base and the right and left shoulder joint point.
4.  I calculate the span vectors of this plane, starting from the spine base.
5.  I calculate the normal vector of the plane from these two span vectors (cross product)   
6.  The calculated vector (spine base to right hip), which represents the x-axis, and the calculated normal vector also span a new plane. For this plane we calculate the normal vector again (cross product). This vector represents the new y-axis.
7.  We calculate one last time the cross product of x-axis and y-axis. This results in the z-axis.
8.  We set our rotation matrix to M (vec_x, vec_y, vec_z)

The calculated coordinate system always points with its y-axis from the spine base towards the shoulders and with the x-axis always towards the right hip. 
The disadvantage of this method is that poses in which the user makes a hump result in a hip movement, although this may did not happen.

**Comment by bsubbaraman** [comment]
Great, thanks for posting your solution! Closing now.
