### ISSUE TITLE
Dual RealSense Person Tracking Setup

### ISSUE THREAD

**Issue by Julian243** [OpenPTrack/open_ptrack_v2#116]
Hello,
I read in issue #51 that tracking results with realsense cameras were pretty bad. Does anyone have experience with tracking results for realsense with v2.2 (released in december)?
As I only have one PC that is powerful enough I was also wondering whether dual camera person tracking on a single PC works sufficient enough. My PC is equipped with an Intel i7-6700K with 4 GHz, 16 GB RAM and a GeForce RTX 2080 Ti.
If anyone has experience please let me know!
Thanks a lot!

**Comment by DiegoJRR** [comment]
Any updates on this? Are the results with the Intel RealSense D435i also bad?

**Comment by bsubbaraman** [comment]
We've seen decent results with the RealSense after [tuning tracking parameters](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Imager-Settings) based on your environment. For example, here is a [video](https://drive.google.com/file/d/13LoLB0SY8ZAfVssTkjP4odUlWfoDjTFn/view?usp=sharing) I recently took of a single camera RealSense. Before tuning, however, you may seen many erroneous tracks. Over larger distances/bigger spaces than that shown in the video, the RealSense quality decreases due to pointcloud noise.

Running two RealSense from a single machine _should_ work out of the box, but it hasn't been tested as I only have 1 here in the lab. To preemptively provide debugging direction, it might take a bit of editing [listener.py](https://github.com/OpenPTrack/open_ptrack_v2/blob/1804/opt_calibration/apps/listener.py) to ensure the serial number/unique identification of each Realsense is properly handled. Do you plan on using multiple modules (person + skeleton + object) or just person tracking? I would expect some drop in fps/quality if using multiple modules, but two person tracking instances shouldn't be a problem given your setup.

Let me know if you have any more questions!

**Comment by Julian243** [comment]
> 
> 
> We've seen decent results with the RealSense after [tuning tracking parameters](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Imager-Settings) based on your environment. For example, here is a [video](https://drive.google.com/file/d/13LoLB0SY8ZAfVssTkjP4odUlWfoDjTFn/view?usp=sharing) I recently took of a single camera RealSense. Before tuning, however, you may seen many erroneous tracks. Over larger distances/bigger spaces than that shown in the video, the RealSense quality decreases due to pointcloud noise.
> 
> Running two RealSense from a single machine _should_ work out of the box, but it hasn't been tested as I only have 1 here in the lab. To preemptively provide debugging direction, it might take a bit of editing [listener.py](https://github.com/OpenPTrack/open_ptrack_v2/blob/1804/opt_calibration/apps/listener.py) to ensure the serial number/unique identification of each Realsense is properly handled. Do you plan on using multiple modules (person + skeleton + object) or just person tracking? I would expect some drop in fps/quality if using multiple modules, but two person tracking instances shouldn't be a problem given your setup.
> 
> Let me know if you have any more questions!

Thanks a lot for your response!! I wanted to use the skeleton tracking module as well. I think just the skeleton tracking module itself might be sufficient. Do you happen to know what results to expect in terms of accuracy and reliablity?

Thanks a lot for your help!

**Comment by jburkeucla** [comment]
Performance depends a lot on the circumstances.  We've been focusing on skeleton tracking for recognition rather than real-time use, but performance in small spaces with good intrinsic and extrinsic calibration is reasonable but still sort of noisy.
