### ISSUE TITLE
Deployment Guide Page Required for Face Recognition

### ISSUE THREAD

**Issue by SimeonOA** [OpenPTrack/open_ptrack_v2#30]
We need to add a deployment guide page that provides helpful hints on how to use the Face Recognition module in OpenPTrack v2.

**Comment by Tobix99** [comment]
Hey, yes, could you do that? I'm trying to run it on my machines (do all the staps fro the wiki page for multi cam detection with faces) and literally nothing is happening.

**Comment by SimeonOA** [comment]
Hi Tobixx99,

Please confirm that all dependencies are installed already: OpenPTrack, OpenFace, dlib, torch7. 
See [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Face-Detection-and-Recognition
) .

If all dependencies are installed and it is still not working, please provide what results you are seeing.

Thanks 
Simeon

**Comment by Tobix99** [comment]
Hey Simeon,

I'm using the docker version of openPTrack with 2 kinect sensors (2 nodes with i7 and Nvidia Quadro Cards) and 1 extra PC dedicated as a master. I've read in the wiki, that the dependecies should be installed in the docker version (?). 

So I've done everthing listed in the wiki page for face detection --> I got no error and also succsessfully uploaded an image. But when I run everything I don't get any eroor, but also no detection or similar.

**Comment by samamin** [comment]
Hi Tobix99,

Do you have OPT tracking/detection running before running the face detection/recognition nodes?

Sam

**Comment by Tobix99** [comment]
Yes, I do. The Start routine is the following: 

**Master:** `roslaunch tracking tracking_node.launch`
**Nodes:** `roslaunch detection detection_node_<sensor>.launch`

**Then on the Nodes:** `roslaunch recognition face_detection_and_feature_extraction.launch sensor_name:="<sensor>"`

**And finally on the Master:** `rosrun recognition face_recognition_node`

I tried running the visualizer on the master (`rosrun recognition recognition_visualization_node.py`),but it has not shown anything. And I'm not exactly sure where to look, if it's detecting, but I have look in every topic displayed in Rviz. I think it should pelace the ID with the name, or am I wrong?

**Comment by samamin** [comment]
Hi Tobias,

Could you please share what you're seeing in the console from the `recognition` nodes? Yeah, the visualizer should have dots with IDs or names associated. 

Thanks,
Sam

**Comment by Tobix99** [comment]
Hey Sam,

I've gatherd the logs:

**Command:** `roslaunch tracking tracking_node.launch`

[Master](https://pastebin.com/ZpiDzrJp)

**Command:** `roslaunch detection detection_node_"NAME".launch`   
--> I exchanged NAME correctly

[Kinect01](https://pastebin.com/ARyXq6Kp)
[Kinect02](https://pastebin.com/m9uLcwZd)

**Command:** `roslaunch recognition face_detection_and_feature_extraction.launch sensor_name:="NAME""<sensor>"`   
--> I exchanged NAME correctly

[Kinect01](https://pastebin.com/1zLu1LB4)
[Kinect02](https://pastebin.com/NY1WsssQ)

**Command:** `rosrun recognition face_recognition_node`

[Master](https://pastebin.com/Y48TCcWL)

**Command:** `rosrun recognition recognition_visualization_node.py`

[Master](https://pastebin.com/zf2HpYYX)



I've **shortenend** the **detection logs** in the middle, because they where to big for pastbin. And also the **tracking log** from the Master is not fully there, because the terminal window did't go back as far, when I'm tracking, so there is only the beginning. If you need some stuff from the shortened logs, then I will try to get it.

Tobias

**Comment by samamin** [comment]
Hi Tobias,

I wanted to get back to you -- the issue is occurring here, in your recognition nodes: `[WARN] [1552984807.184253]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.` This is not normal, but I'm not yet sure why it is happening for you.

**Comment by jburkeucla** [comment]
Does basic detection and tracking work properly? Could you calibrate? We should confirm this issue is limited to recognition. Thanks!
________________________________

**Comment by Tobix99** [comment]
Hey Sam, Hey Jeff,

yes, I've done intrinsic and extrinsic calibration and it work's like a charm. Object detection, skeleton detetion and person tracking all works.

My setup is, that I've 3 Workstations, which all run the docker and are all connected via one ethernet switch (with one upstream internet port). Two of the WS have a kinect attachted and the third runs as a master for displaying Rviz. 

Tobias

**Comment by Tobix99** [comment]
Hey guys,

have you had some time too look into the problem? Should I open a new issue for that problem?

I don't want to annoy you guys and I know you had better stuff to do, but I want to know the status of my problem :).

Tobias

**Comment by jburkeucla** [comment]
Let me check.

**Comment by Tobix99** [comment]
Hey @samamin and @jburkeucla ,

can I help you to solve this problem in any way?

Tobias

**Comment by samamin** [comment]
Hi Tobias,

Sorry for the delay. I'll try to provide some debugging code this week so we can figure out where this is going wrong.

**Comment by Tobix99** [comment]
Hey,
I'm now a bit familiar with openPtrack and found the logs to my test this morning (in .ros/logs). I've zip'd them and attechted to this issue. I put the drag and drop and visualizer log in the face folder in the zip. Maybe they can help you too.

Tobias

[logs.zip](https://github.com/OpenPTrack/open_ptrack_v2/files/3181408/logs.zip)

**Comment by samamin** [comment]
Hi Tobias! I'm glad you were able to resolve this. Sorry I wasn't able to be helpful in the end! Please let us know of any more issues. 

Best,
Sam
