### ISSUE TITLE
Error building dev branch: Can't find ddynamic_reconfigure

### ISSUE THREAD

**Issue by jefft0** [OpenPTrack/open_ptrack_v2#70]
I'm trying to build the dev branch. (I already have the docker image openptrack/open_ptrack-dep.)

    git clone https://github.com/OpenPTrack/open_ptrack_v2
    cd open_ptrack_v2/docker/open_ptrack
    git checkout dev
    sudo docker build -t openptrack/open_ptrack:dev .

I get the following error:

    Could not find the required component 'ddynamic_reconfigure'.

**Comment by bsubbaraman** [comment]
I think this is due to changes in the realsense-ros wrapper.  I ran into the same problem, and per [this issue](https://github.com/IntelRealSense/realsense-ros/issues/812), added the following to line 17 of /docker/open_ptrack/Dockerfile:

`&& apt-get install ros-kinetic-ddynamic-reconfigure`

and the build succeeded.  Let me know if this also resolves your issue!

**Comment by jburkeucla** [comment]
If this works, please commit the fix.
Jeff

**Comment by SimeonOA** [comment]
Blair will test to ensure that the fix works for Kinect as well and does not break anything since the dev branch currently works for both the realsense and Kinect devices.

Thanks 

Simeon.

**Comment by jefft0** [comment]
Hi @bsubbaraman . Your solution worked for me. Are you planning to merge it?

**Comment by bsubbaraman** [comment]
I tested to ensure the fix didn't break anything with the Kinect (it didn't) and the change has been pushed.
